import Link from "next/link";
import { notFound } from "next/navigation";
import { Check, X } from "lucide-react";
import { packages } from "@/lib/catalog";
import EnquiryForm from "@/components/EnquiryForm";

const itinerary = [["Day 1–2", "Arrive & settle in", "A private welcome, a thoughtful stay and time to discover the local rhythm."], ["Day 3–5", "Go deeper", "Guided experiences, unhurried meals and memorable landscapes."], ["Day 6–7", "Leave with stories", "One last immersive day before a seamless onward journey."]];

export default async function PackageDetail({ params }) {
  const { slug } = await params;
  const trip = packages.find((p) => p.slug === slug);
  if (!trip) return notFound();
  return <main className="bg-[#f8f7f2]"><div className="min-h-[460px] bg-cover bg-center" style={{ backgroundImage: `linear-gradient(90deg,rgba(4,45,44,.88),rgba(4,45,44,.12)),url(${trip.image})` }}><div className="mx-auto max-w-6xl px-6 py-8 text-white"><Link href="/packages" className="text-sm font-bold">← All journeys</Link><div className="mt-32 max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#f4c96a]">{trip.category} · {trip.duration}</p><h1 className="mt-3 font-serif text-5xl sm:text-6xl">{trip.name}</h1><p className="mt-5 text-lg text-white/80">{trip.route}</p></div></div></div><div className="mx-auto grid max-w-6xl gap-10 px-6 py-14 lg:grid-cols-[1.45fr_.75fr]"><div><h2 className="font-serif text-3xl">The experience</h2><p className="mt-4 leading-8 text-slate-600">{trip.summary} Designed with a balanced pace, warm hosts and the confidence of an on-ground team at every turn.</p><h2 className="mt-12 font-serif text-3xl">Your itinerary</h2><div className="mt-5 space-y-4">{itinerary.map(([day, title, text]) => <div key={day} className="rounded-2xl bg-white p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#d4664d]">{day}</p><h3 className="mt-1 font-bold">{title}</h3><p className="mt-2 text-sm text-slate-500">{text}</p></div>)}</div><div className="mt-12 grid gap-5 sm:grid-cols-2"><div><h3 className="font-bold">Included</h3>{["Handpicked accommodation", "Daily breakfast", "Private transfers", "Local experiences"].map((x) => <p key={x} className="mt-3 flex gap-2 text-sm text-slate-600"><Check size={17} className="text-teal-700" />{x}</p>)}</div><div><h3 className="font-bold">Not included</h3>{["International flights", "Visa fees", "Personal expenses", "Travel insurance"].map((x) => <p key={x} className="mt-3 flex gap-2 text-sm text-slate-600"><X size={17} className="text-[#d4664d]" />{x}</p>)}</div></div></div><aside><div className="sticky top-6 rounded-3xl bg-[#073b3a] p-6 text-white"><p className="text-sm text-white/65">Starting from</p><p className="mt-1 font-serif text-4xl">{trip.price}</p><p className="mt-1 text-xs text-white/60">per person, twin share</p><hr className="my-6 border-white/15" /><p className="mb-4 font-serif text-2xl">Make it yours</p><EnquiryForm /></div></aside></div></main>;
}
